train:
  num_runs: 1
  pop_size: 100
  num_gens: 10
  multiprocessing: true

nn:
  input_size: 20
  hidden_size: 10
  output_size: 5

evolve:
  cross_prob: 0.5
  mutation_prob: 0.2
  lambda_coeff: 3
  selection_pressure: 3
  sigma_mutation: 1
  indpb_mutation: 0.5
  eta_crossover: 0.2
  selection_strategy: "plus" # Can be either "comma" or "plus"

