train:
  pop_size: 100
  num_gens: 100

nn:
  input_size: 20
  hidden_size: 10
  output_size: 5

evolve:
  cross_prob: 0.8
  mutation_prob: 0.8
  lambda_coeff: 7
  selection_pressure: 3
  sigma_mutation: 1
  indpb_mutation: 0.5
  eta_crossover: 0.2
  selection_strategy: "plus" # Can be either "comma" or "plus"

